# https://docs.travis-ci.com/user/deployment/pages/
# https://docs.travis-ci.com/user/languages/go/
# https://docs.travis-ci.com/user/customizing-the-build/

language: go

python:
    - master

# before_install
# install - install any dependencies required
install:
    - wget --no-check-certificate --content-disposition https://github.com/gohugoio/hugo/releases/download/v0.53/hugo_0.53_Linux-64bit.deb
    - sudo apt install ./hugo_0.53_Linux-64bit.deb
before_script:
    - rm -rf public 2> /dev/null

# script - run the build script
script:
    - git submodule add -f -b master https://github.com/PrasannaNatarajan/PrasannaNatarajan.github.io.git public
    - hugo

after_success:
  - cd ./public
  - git config user.email ${GITHUB_EMAIL}
  - git config user.name ${GITHUB_USERNAME}
  - git remote -v
  - rev=$(git rev-parse --short HEAD)
  - git add .
  - git commit -m "deployed with latest ${rev}"
  - git push origin master

# deploy:
#   provider: pages
#   skip-cleanup: true
#   github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
#   email: $GITHUB_EMAIL
#   name: $GITHUB_USERNAME
#   verbose: true
#   keep-history: true
#   local-dir: public
#   on:
#     repo: https://github.com/PrasannaNatarajan/PrasannaNatarajan.github.io

#     branches:
#       only:
#         - master   # branch contains Hugo generator code